/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agroshift.view;

import agroshift.controller.AlertController;
import agroshift.model.Alerta;
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author victo
 */
public class AlertView extends javax.swing.JFrame {

    /**
     * Creates new form AlertView
     */
    public AlertView() {
        initComponents();
        cargarAlertasEnCurso();
        setTitle("Alertas en curso");
        setLocationRelativeTo(null);
        if(AlertController.hayAlertasVencidas()){
            btnExpiredAlerts.setVisible(true);
        } else btnExpiredAlerts.setVisible(false);
        
    }
    private ArrayList<Alerta> alertasEnCurso = new ArrayList<>();
    
     private void formatoTabla(){
                
        int[] weights = {75,25};
            
        for(int i = 0; i < tblAlertasEnCurso.getColumnCount(); i++){
            tblAlertasEnCurso.getColumnModel().getColumn(i).setPreferredWidth(weights[i]);
        }
        
        DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer();
        headerRenderer.setBackground(new Color(30, 30, 30));
        headerRenderer.setForeground(Color.WHITE);
        headerRenderer.setFont(new Font("Segoe UI",Font.BOLD,14));
        headerRenderer.setOpaque(true);
        headerRenderer.setHorizontalAlignment(SwingConstants.CENTER);
  
        for (int i = 0; i < tblAlertasEnCurso.getModel().getColumnCount(); i++) {          //Recorro y se lo aplico a cada header
            tblAlertasEnCurso.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer);    
        }
        
        DefaultTableCellRenderer cellRenderer = new DefaultTableCellRenderer();
        cellRenderer.setBackground(new Color(240, 240, 240));
        cellRenderer.setForeground(Color.BLACK);
        cellRenderer.setFont(new Font("Segoe UI",Font.PLAIN,13));
        cellRenderer.setOpaque(true);
        cellRenderer.setHorizontalAlignment(SwingConstants.CENTER);
        
        for (int i = 0; i < tblAlertasEnCurso.getColumnCount(); i++) {          //Recorro y se lo aplico a cada header
            tblAlertasEnCurso.getColumnModel().getColumn(i).setCellRenderer(cellRenderer);    
        }
    }
    
    private void cargarAlertasEnCurso(){
        alertasEnCurso = AlertController.obtenerAlertasEnCurso();
        int numberColumns = 2;
        try{
            DefaultTableModel model = new DefaultTableModel(){
                @Override
                public boolean isCellEditable(int i, int i1){
                    return false;
                }
            };
            tblAlertasEnCurso.setModel(model);
            model.addColumn("Alerta");
            model.addColumn("Vencimiento");
            
            formatoTabla();
            
            for(Alerta alerta: alertasEnCurso){
                Object[] rows = new Object[numberColumns];
                rows[0] = alerta.getNombre();
                rows[1] = alerta.getFecha_fin();
                model.addRow(rows);
            }
                
        } catch(Exception e){
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(null,"Error al cargar las alertas");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnBack = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAlertasEnCurso = new javax.swing.JTable();
        btnRevisarAlerta = new javax.swing.JLabel();
        btnNewAlert = new javax.swing.JButton();
        btnEditNoEnCursoAlert = new javax.swing.JButton();
        btnExpiredAlerts = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agroshift/img/back-arrow-75.png"))); // NOI18N
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMouseClicked(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, -1, -1));

        tblAlertasEnCurso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Alerta", "Vencimiento"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblAlertasEnCurso.setRowHeight(22);
        tblAlertasEnCurso.setSelectionBackground(new java.awt.Color(232, 213, 84));
        tblAlertasEnCurso.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(tblAlertasEnCurso);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, -1, 200));

        btnRevisarAlerta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRevisarAlerta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agroshift/img/eye_60.png"))); // NOI18N
        btnRevisarAlerta.setText("REVISAR ALERTA");
        btnRevisarAlerta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRevisarAlertaMouseClicked(evt);
            }
        });
        jPanel1.add(btnRevisarAlerta, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 240, -1, -1));

        btnNewAlert.setText("CREAR ALERTA");
        btnNewAlert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewAlertActionPerformed(evt);
            }
        });
        jPanel1.add(btnNewAlert, new org.netbeans.lib.awtextra.AbsoluteConstraints(583, 435, 120, 30));

        btnEditNoEnCursoAlert.setText("<html><center>EDITAR ALERTAS AUN NO EN CURSO<html>");
        btnEditNoEnCursoAlert.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEditNoEnCursoAlert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditNoEnCursoAlertActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditNoEnCursoAlert, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 130, 50));

        btnExpiredAlerts.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnExpiredAlerts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agroshift/img/expired_50.png"))); // NOI18N
        btnExpiredAlerts.setText("ALERTAS VENCIDAS");
        btnExpiredAlerts.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnExpiredAlertsKeyPressed(evt);
            }
        });
        jPanel1.add(btnExpiredAlerts, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 420, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agroshift/img/fondo_alerta1.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 724, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseClicked
        MainView form = new MainView();
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackMouseClicked

    private void btnRevisarAlertaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRevisarAlertaMouseClicked
        int FILA = tblAlertasEnCurso.getSelectedRow();
        if(FILA != -1){
            CheckAlert form = new CheckAlert(alertasEnCurso.get(FILA));
            form.setVisible(true);
            this.dispose();
        } else{
            JOptionPane.showMessageDialog(null, "Seleccione la alerta");
        }
    }//GEN-LAST:event_btnRevisarAlertaMouseClicked

    private void btnNewAlertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewAlertActionPerformed
        SelectModelAlertView form = new SelectModelAlertView();
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnNewAlertActionPerformed

    private void btnEditNoEnCursoAlertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditNoEnCursoAlertActionPerformed
        NotInProgressAlertsView form = new NotInProgressAlertsView();
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnEditNoEnCursoAlertActionPerformed

    private void btnExpiredAlertsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnExpiredAlertsKeyPressed
        ExpiredAlertsView form = new ExpiredAlertsView();
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnExpiredAlertsKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlertView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlertView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlertView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlertView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlertView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBack;
    private javax.swing.JButton btnEditNoEnCursoAlert;
    private javax.swing.JLabel btnExpiredAlerts;
    private javax.swing.JButton btnNewAlert;
    private javax.swing.JLabel btnRevisarAlerta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAlertasEnCurso;
    // End of variables declaration//GEN-END:variables
}
