/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agroshift.view;

import agroshift.controller.AlertController;
import agroshift.model.Alerta;
import javax.swing.JOptionPane;

/**
 *
 * @author victo
 */
public class CheckAlert extends javax.swing.JFrame {

    /**
     * Creates new form CheckAlert
     */
    public CheckAlert() {
        initComponents();
    }
    public CheckAlert(Alerta alerta) {
        initComponents();
        setTitle("Alerta");
        setLocationRelativeTo(null);
        this.alerta = alerta;
        if(AlertController.setearAlertaVisualizada(alerta.getId_alerta())){
            lblName.setText("<html><center>"+alerta.getNombre()+"<html>");
            lblDescription.setText("<html><center>"+alerta.getDescripcion()+"<html>");
            lblVencimiento.setText(alerta.getFecha_fin());

        } else{
            JOptionPane.showMessageDialog(null, "Error al visualizar alerta");
            AlertView form = new AlertView();
            form.setVisible(true);
            this.dispose();
        }
    }
    public CheckAlert(Alerta alerta,boolean vencida) {      //Llega una vencida
        initComponents();
        llegaUnaVencida = true;
        btnSeguirMostrando.setVisible(false);
        lblVencimientoText.setVisible(false);
        lblVencimiento.setVisible(false);
        this.alerta = alerta;
        if(AlertController.setearAlertaVisualizada(alerta.getId_alerta())){
            lblName.setText("<html><center>"+alerta.getNombre()+"<html>");
            lblDescription.setText("<html><center>"+alerta.getDescripcion()+"<html>");
            lblVencimiento.setText(alerta.getFecha_fin());

        } else{
            JOptionPane.showMessageDialog(null, "Error al visualizar alerta");
            ExpiredAlertsView form = new ExpiredAlertsView();
            form.setVisible(true);
            this.dispose();
        }
    }
    boolean llegaUnaVencida = false;

    Alerta alerta;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        lblDescription = new javax.swing.JLabel();
        btnDeleteAlert = new javax.swing.JButton();
        btnSeguirMostrando = new javax.swing.JButton();
        lblVencimientoText = new javax.swing.JLabel();
        lblVencimiento = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        lblName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblName.setText("<html><center>\"Texto aca\"<html>");

        lblDescription.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDescription.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDescription.setText("Descripcion");
        lblDescription.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        btnDeleteAlert.setText("DESCARTAR ALERTA");
        btnDeleteAlert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteAlertActionPerformed(evt);
            }
        });

        btnSeguirMostrando.setText("SEGUIR MOSTRANDO");
        btnSeguirMostrando.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeguirMostrandoActionPerformed(evt);
            }
        });

        lblVencimientoText.setText("Vencimiento:");

        lblVencimiento.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lblVencimiento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVencimiento.setText("2021-01-01");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDescription, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblName)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnDeleteAlert)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 386, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lblVencimientoText)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblVencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnSeguirMostrando, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(lblDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVencimientoText)
                    .addComponent(lblVencimiento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteAlert, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSeguirMostrando, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteAlertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteAlertActionPerformed
        if(llegaUnaVencida){
          if(AlertController.eliminarAlerta(alerta.getId_alerta())){
                JOptionPane.showMessageDialog(null,"Alerta descartada");
                ExpiredAlertsView form = new ExpiredAlertsView();
                form.setVisible(true);
                this.dispose();
            }   
        }else{
           if(AlertController.eliminarAlerta(alerta.getId_alerta())){
                JOptionPane.showMessageDialog(null,"Alerta descartada");
                AlertView form = new AlertView();
                form.setVisible(true);
                this.dispose();
            }  
        }
        
    }//GEN-LAST:event_btnDeleteAlertActionPerformed

    private void btnSeguirMostrandoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeguirMostrandoActionPerformed
        AlertView form = new AlertView();
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSeguirMostrandoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheckAlert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheckAlert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheckAlert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckAlert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CheckAlert().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteAlert;
    private javax.swing.JButton btnSeguirMostrando;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblVencimiento;
    private javax.swing.JLabel lblVencimientoText;
    // End of variables declaration//GEN-END:variables
}
