/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agroshift.view;

import agroshift.controller.AlertController;
import agroshift.model.Alerta;
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author victo
 */
public class ExpiredAlertsView extends javax.swing.JFrame {

    /**
     * Creates new form ExpiredAlertsView
     */
    public ExpiredAlertsView() {
        initComponents();
        cargarAlertasVencidas();
        setTitle("Actualizar alertas");
        setLocationRelativeTo(null);
    }

    private ArrayList<Alerta> alertasVencidas = new ArrayList<>();
    
     private void formatoTabla(){
                
        int[] weights = {75,25};
            
        for(int i = 0; i < tblAlertasVencidas.getColumnCount(); i++){
            tblAlertasVencidas.getColumnModel().getColumn(i).setPreferredWidth(weights[i]);
        }
        
        DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer();
        headerRenderer.setBackground(new Color(30, 30, 30));
        headerRenderer.setForeground(Color.WHITE);
        headerRenderer.setFont(new Font("Segoe UI",Font.BOLD,14));
        headerRenderer.setOpaque(true);
        headerRenderer.setHorizontalAlignment(SwingConstants.CENTER);
  
        for (int i = 0; i < tblAlertasVencidas.getModel().getColumnCount(); i++) {          //Recorro y se lo aplico a cada header
            tblAlertasVencidas.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer);    
        }
        
        DefaultTableCellRenderer cellRenderer = new DefaultTableCellRenderer();
        cellRenderer.setBackground(new Color(240, 240, 240));
        cellRenderer.setForeground(Color.BLACK);
        cellRenderer.setFont(new Font("Segoe UI",Font.PLAIN,13));
        cellRenderer.setOpaque(true);
        cellRenderer.setHorizontalAlignment(SwingConstants.CENTER);
        
        for (int i = 0; i < tblAlertasVencidas.getColumnCount(); i++) {          //Recorro y se lo aplico a cada header
            tblAlertasVencidas.getColumnModel().getColumn(i).setCellRenderer(cellRenderer);    
        }
    }
    
    private void cargarAlertasVencidas(){
        alertasVencidas = AlertController.obtenerAlertasVencidas();
        int numberColumns = 2;
        try{
            DefaultTableModel model = new DefaultTableModel(){
                @Override
                public boolean isCellEditable(int i, int i1){
                    return false;
                }
            };
            tblAlertasVencidas.setModel(model);
            model.addColumn("Alerta");
            model.addColumn("Finalizó");
            
            formatoTabla();
            
            for(Alerta alerta: alertasVencidas){
                Object[] rows = new Object[numberColumns];
                rows[0] = alerta.getNombre();
                rows[1] = alerta.getFecha_fin();
                model.addRow(rows);
            }
                
        } catch(Exception e){
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(null,"Error al cargar las alertas vencidas");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JLabel();
        btnDescartarTodas = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAlertasVencidas = new javax.swing.JTable();
        btnRevisarAlerta = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agroshift/img/back-arrow-75.png"))); // NOI18N
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMouseClicked(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, -1, -1));

        btnDescartarTodas.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btnDescartarTodas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDescartarTodas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agroshift/img/delete_50.png"))); // NOI18N
        btnDescartarTodas.setText("DESCARTAR TODAS LAS ALERTAS VENCIDAS");
        btnDescartarTodas.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnDescartarTodas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDescartarTodasMouseClicked(evt);
            }
        });
        btnDescartarTodas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnDescartarTodasKeyPressed(evt);
            }
        });
        getContentPane().add(btnDescartarTodas, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 420, -1, -1));

        tblAlertasVencidas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Alerta", "Vencimiento"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblAlertasVencidas.setRowHeight(22);
        tblAlertasVencidas.setSelectionBackground(new java.awt.Color(232, 213, 84));
        tblAlertasVencidas.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(tblAlertasVencidas);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, -1, 200));

        btnRevisarAlerta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRevisarAlerta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agroshift/img/eye_60.png"))); // NOI18N
        btnRevisarAlerta.setText("REVISAR ALERTA");
        btnRevisarAlerta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRevisarAlertaMouseClicked(evt);
            }
        });
        getContentPane().add(btnRevisarAlerta, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 240, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agroshift/img/fondo_alerta1.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 724, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRevisarAlertaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRevisarAlertaMouseClicked
        int FILA = tblAlertasVencidas.getSelectedRow();
        if(FILA != -1){
            CheckAlert form = new CheckAlert(alertasVencidas.get(FILA),true);
            form.setVisible(true);
            this.dispose();
        } else{
            JOptionPane.showMessageDialog(null, "Seleccione la alerta");
        }
    }//GEN-LAST:event_btnRevisarAlertaMouseClicked

    private void btnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseClicked
        AlertView form = new AlertView();
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackMouseClicked

    private void btnDescartarTodasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnDescartarTodasKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDescartarTodasKeyPressed

    private void btnDescartarTodasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDescartarTodasMouseClicked
        if(AlertController.eliminarAlertasVencidas()){
            cargarAlertasVencidas();
        }
    }//GEN-LAST:event_btnDescartarTodasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExpiredAlertsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExpiredAlertsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExpiredAlertsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExpiredAlertsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExpiredAlertsView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBack;
    private javax.swing.JLabel btnDescartarTodas;
    private javax.swing.JLabel btnRevisarAlerta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAlertasVencidas;
    // End of variables declaration//GEN-END:variables
}
