/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agroshift.view;

import agroshift.controller.AlertController;
import agroshift.util.UserLogin;

/**
 *
 * @author victo
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
        lblCantidadAlertas.setText(String.valueOf(AlertController.obtenerCantidadAlertasEnCurso()));
        setTitle("Menu Principal");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblCantidadAlertas = new javax.swing.JLabel();
        btnRentas = new javax.swing.JButton();
        btnAlertas = new javax.swing.JButton();
        btnEquipo = new javax.swing.JButton();
        btnEmpleados = new javax.swing.JButton();
        btnClientes = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnModificarClave1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCantidadAlertas.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblCantidadAlertas.setForeground(new java.awt.Color(255, 255, 255));
        lblCantidadAlertas.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCantidadAlertas.setText("0");
        jPanel1.add(lblCantidadAlertas, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 420, 70, 40));

        btnRentas.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btnRentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agroshift/img/rent_ico60.png"))); // NOI18N
        btnRentas.setText("RENTAS");
        btnRentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRentasActionPerformed(evt);
            }
        });
        jPanel1.add(btnRentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 160, 70));

        btnAlertas.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btnAlertas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agroshift/img/alert_ico60.png"))); // NOI18N
        btnAlertas.setText("ALERTAS");
        btnAlertas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAlertas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlertasActionPerformed(evt);
            }
        });
        jPanel1.add(btnAlertas, new org.netbeans.lib.awtextra.AbsoluteConstraints(776, 460, 160, 60));

        btnEquipo.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btnEquipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agroshift/img/equip_ico60.png"))); // NOI18N
        btnEquipo.setText("<html><center>EQUIPO AGRÍCOLA</html>");
        btnEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEquipoActionPerformed(evt);
            }
        });
        jPanel1.add(btnEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 110, 160, 70));

        btnEmpleados.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btnEmpleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agroshift/img/employee_ico60.png"))); // NOI18N
        btnEmpleados.setText("PERSONAL");
        btnEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpleadosActionPerformed(evt);
            }
        });
        jPanel1.add(btnEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 310, 160, 70));

        btnClientes.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agroshift/img/client_ico60.png"))); // NOI18N
        btnClientes.setText("CLIENTES");
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });
        jPanel1.add(btnClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 160, 70));

        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, -1, -1));

        btnModificarClave1.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btnModificarClave1.setText("Modificar clave");
        btnModificarClave1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarClave1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificarClave1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 20, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agroshift/img/fondo_maquinaria5.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRentasActionPerformed
        RentsView form = new RentsView();
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRentasActionPerformed

    private void btnAlertasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlertasActionPerformed

        AlertView form = new AlertView();
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAlertasActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        if(UserLogin.getInstance().is_admin){
            AdminMainView form = new AdminMainView();
            form.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEquipoActionPerformed
        EquipmentView form = new EquipmentView();
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnEquipoActionPerformed

    private void btnEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpleadosActionPerformed
        EmployeesView form = new EmployeesView();
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnEmpleadosActionPerformed

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        ClientsView form = new ClientsView();
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnModificarClave1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarClave1ActionPerformed
        NewPasswordView form = new NewPasswordView();
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnModificarClave1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlertas;
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnEmpleados;
    private javax.swing.JButton btnEquipo;
    private javax.swing.JButton btnModificarClave1;
    private javax.swing.JButton btnRentas;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCantidadAlertas;
    // End of variables declaration//GEN-END:variables
}
