/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agroshift.view;

import agroshift.controller.AlertController;
import agroshift.model.Alerta;
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author victo
 */
public class NotInProgressAlertsView extends javax.swing.JFrame {

    /**
     * Creates new form NotInProgressAlertsView
     */
    public NotInProgressAlertsView() {
        initComponents();
        cargarAlertasNoEnCurso();
        setTitle("Actualizar alertas");
        setLocationRelativeTo(null);
    }

    private ArrayList<Alerta> alertasNoEnCurso = new ArrayList<>();
    
     private void formatoTabla(){
                
        int[] weights = {75,25};
            
        for(int i = 0; i < tblAlertasNoEnCurso.getColumnCount(); i++){
            tblAlertasNoEnCurso.getColumnModel().getColumn(i).setPreferredWidth(weights[i]);
        }
        
        DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer();
        headerRenderer.setBackground(new Color(30, 30, 30));
        headerRenderer.setForeground(Color.WHITE);
        headerRenderer.setFont(new Font("Segoe UI",Font.BOLD,14));
        headerRenderer.setOpaque(true);
        headerRenderer.setHorizontalAlignment(SwingConstants.CENTER);
  
        for (int i = 0; i < tblAlertasNoEnCurso.getModel().getColumnCount(); i++) {          //Recorro y se lo aplico a cada header
            tblAlertasNoEnCurso.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer);    
        }
        
        DefaultTableCellRenderer cellRenderer = new DefaultTableCellRenderer();
        cellRenderer.setBackground(new Color(240, 240, 240));
        cellRenderer.setForeground(Color.BLACK);
        cellRenderer.setFont(new Font("Segoe UI",Font.PLAIN,13));
        cellRenderer.setOpaque(true);
        cellRenderer.setHorizontalAlignment(SwingConstants.CENTER);
        
        for (int i = 0; i < tblAlertasNoEnCurso.getColumnCount(); i++) {          //Recorro y se lo aplico a cada header
            tblAlertasNoEnCurso.getColumnModel().getColumn(i).setCellRenderer(cellRenderer);    
        }
    }
    
    private void cargarAlertasNoEnCurso(){
        alertasNoEnCurso = AlertController.obtenerAlertasNoEnCurso();
        int numberColumns = 2;
        try{
            DefaultTableModel model = new DefaultTableModel(){
                @Override
                public boolean isCellEditable(int i, int i1){
                    return false;
                }
            };
            tblAlertasNoEnCurso.setModel(model);
            model.addColumn("Alerta");
            model.addColumn("Inicio");
            
            formatoTabla();
            
            for(Alerta alerta: alertasNoEnCurso){
                Object[] rows = new Object[numberColumns];
                rows[0] = alerta.getNombre();
                rows[1] = alerta.getFecha_inicio_en_curso();
                model.addRow(rows);
            }
                
        } catch(Exception e){
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(null,"Error al cargar las alertas");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtInicio = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtVencimiento = new javax.swing.JTextField();
        btnActualizar = new javax.swing.JButton();
        btnBack1 = new javax.swing.JLabel();
        btnDescartar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAlertasNoEnCurso = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agroshift/img/back-arrow-75.png"))); // NOI18N
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMouseClicked(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, -1, -1));

        txtInicio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 390, 100, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Inicio");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 390, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Descripcion");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, -1, -1));

        txtNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, 360, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Vencimiento");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 390, -1, -1));

        txtVencimiento.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtVencimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 390, 100, -1));

        btnActualizar.setText("ACTUALIZAR ALERTA");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(553, 435, 160, 40));

        btnBack1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agroshift/img/back-arrow-75.png"))); // NOI18N
        btnBack1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBack1MouseClicked(evt);
            }
        });
        getContentPane().add(btnBack1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, -1, -1));

        btnDescartar.setText("DESCARTAR");
        btnDescartar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescartarActionPerformed(evt);
            }
        });
        getContentPane().add(btnDescartar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 120, -1));

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        txtDescripcion.setToolTipText("Ingrese la descripcion");
        jScrollPane2.setViewportView(txtDescripcion);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, 360, 80));

        tblAlertasNoEnCurso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Alerta", "Inicio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblAlertasNoEnCurso.setRowHeight(22);
        tblAlertasNoEnCurso.setSelectionBackground(new java.awt.Color(232, 213, 84));
        tblAlertasNoEnCurso.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tblAlertasNoEnCurso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAlertasNoEnCursoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblAlertasNoEnCurso);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, -1, 200));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agroshift/img/fondo_alerta1.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 724, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseClicked
        MainView form = new MainView();
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackMouseClicked

    private void btnBack1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBack1MouseClicked
        MainView form = new MainView();
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBack1MouseClicked

    Alerta alerta_seleccionada;
    
    private void tblAlertasNoEnCursoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAlertasNoEnCursoMouseClicked
        int FILA = tblAlertasNoEnCurso.getSelectedRow();
        if(FILA != -1){
            alerta_seleccionada = alertasNoEnCurso.get(FILA);
            txtDescripcion.setText(alerta_seleccionada.getDescripcion());
            txtNombre.setText(alerta_seleccionada.getNombre());
            txtInicio.setText(alerta_seleccionada.getFecha_inicio_en_curso());
            txtVencimiento.setText(alerta_seleccionada.getFecha_fin());
        }
    }//GEN-LAST:event_tblAlertasNoEnCursoMouseClicked

    //IMPLEMENTAR
    private boolean validarCampos(){
        return true;
    }
    private void setearCampos(){
        alerta_seleccionada.setDescripcion(txtDescripcion.getText().toUpperCase());
        alerta_seleccionada.setNombre(txtNombre.getText().toUpperCase());
        alerta_seleccionada.setFecha_fin(txtVencimiento.getText());
        alerta_seleccionada.setFecha_inicio_en_curso(txtInicio.getText());
    }
    
    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        if(validarCampos()){
            setearCampos();
            if(AlertController.actualizarAlerta(alerta_seleccionada)){
                NotInProgressAlertsView form = new NotInProgressAlertsView();
                form.setVisible(true);
                this.dispose();
            }
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnDescartarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescartarActionPerformed
        int FILA = tblAlertasNoEnCurso.getSelectedRow();
        if(FILA != -1){
            if(AlertController.eliminarAlerta(alertasNoEnCurso.get(FILA).getId_alerta())){
                JOptionPane.showMessageDialog(null, "Alerta descartada");
                cargarAlertasNoEnCurso();
            }
        }
    }//GEN-LAST:event_btnDescartarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NotInProgressAlertsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NotInProgressAlertsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NotInProgressAlertsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NotInProgressAlertsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NotInProgressAlertsView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JLabel btnBack;
    private javax.swing.JLabel btnBack1;
    private javax.swing.JButton btnDescartar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblAlertasNoEnCurso;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtInicio;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtVencimiento;
    // End of variables declaration//GEN-END:variables
}
