/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agroshift.view;

import agroshift.controller.EquipmentController;
import agroshift.model.EquipoAgricola;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author victo
 */
public class UpdateEquipmentView extends javax.swing.JFrame {

    /**
     * Creates new form SeeEquipmentView
     */
    public UpdateEquipmentView() {
        initComponents();
        setTitle("Ver detalles del equipo");
        setLocationRelativeTo(null);    
    }
    EquipoAgricola equipoSeleccionado;
    
    public UpdateEquipmentView(EquipoAgricola equipoAgricola) {
        initComponents();
        setTitle("Ver detalles del equipo");
        equipoSeleccionado = equipoAgricola;
        setLocationRelativeTo(null);
        cargarEstados();
        cargarTipos();
        cargarDatos(equipoAgricola);      
        
    }
    
    private void cargarTipos(){
        ArrayList<String> tipos = EquipmentController.obtenerTodosTipos();
        for(String tipo:tipos){
            cbxTypes.addItem(tipo);
        }
        cbxTypes.setSelectedItem(EquipmentController.obtenerTipoPorId(equipoSeleccionado.getId_tipo()));
    }
    private void cargarEstados(){
        ArrayList<String> estados = EquipmentController.obtenerTodosEstados();
        for(String est:estados){
            cbxStates.addItem(est);
        }
        cbxStates.setSelectedItem(EquipmentController.obtenerEstadoPorId(equipoSeleccionado.getId_estado()));
    }
    
    private void cargarDatos(EquipoAgricola equipo){
        txtAnioAdq.setText(equipo.getAdquisicion().substring(0,4));
        txtMesAdq.setText(equipo.getAdquisicion().substring(5,7));
        txtDiaAdq.setText(equipo.getAdquisicion().substring(8));
        txtCodigo.setText(equipo.getCodigo());
        txtDescripcion.setText(equipo.getDescripcion());
        txtMarca.setText(equipo.getMarca());
        txtModelo.setText(equipo.getModelo());
        cbxStates.setSelectedItem(EquipmentController.obtenerEstadoPorId(equipo.getId_estado()));
        cbxTypes.setSelectedItem(EquipmentController.obtenerTipoPorId(equipo.getId_tipo()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cbxTypes = new javax.swing.JComboBox<>();
        cbxStates = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        btnNew = new javax.swing.JLabel();
        btnBack1 = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtAnioAdq = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtDiaAdq = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        txtMesAdq = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbxTypes.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPanel1.add(cbxTypes, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 190, -1));

        cbxStates.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPanel1.add(cbxStates, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 200, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("MARCA");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 550, -1));

        btnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agroshift/img/save_75.png"))); // NOI18N
        btnNew.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNewMouseClicked(evt);
            }
        });
        jPanel1.add(btnNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 620, -1, -1));

        btnBack1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agroshift/img/back-arrow-75.png"))); // NOI18N
        btnBack1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBack1MouseClicked(evt);
            }
        });
        jPanel1.add(btnBack1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 620, -1, -1));

        txtMarca.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 13)); // NOI18N
        txtMarca.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMarcaActionPerformed(evt);
            }
        });
        jPanel1.add(txtMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 230, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("TIPO                                      ESTADO");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 550, -1));

        txtModelo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        txtModelo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 230, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("MODELO");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 550, -1));

        txtCodigo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        txtCodigo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 230, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("CODIGO");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 550, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("ADQUISICION");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 550, -1));

        txtAnioAdq.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        txtAnioAdq.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtAnioAdq, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 550, 70, 40));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("DESCRIPCION");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 550, -1));

        txtDiaAdq.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        txtDiaAdq.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtDiaAdq, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 550, 50, 40));

        txtDescripcion.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        txtDescripcion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, 230, 40));

        txtMesAdq.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        txtMesAdq.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtMesAdq, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 550, 50, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agroshift/img/fondo_maquinaria2.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBack1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBack1MouseClicked
        EquipmentView form = new EquipmentView();
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBack1MouseClicked

    private void txtMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMarcaActionPerformed

    private boolean fechaMenorIgualHoy(String dia, String mes, String anio){
        try{
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        
            String date = anio+"-"+mes+"-"+dia;
            LocalDate parsedDate = LocalDate.parse(date,formatter);
            if(parsedDate.isAfter(LocalDate.now())){            //SI LA FECHA ES POSTERIOR A HOY (OSEA QUE NO CORRESPONDE)
                return false;
            } else return true;
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error al parsear la fecha");
            return false;
        }
    }
    
    private boolean validarFecha(){
        try{
            if(Integer.parseInt(txtDiaAdq.getText()) > 0 && Integer.parseInt(txtDiaAdq.getText()) < 32){
                if(Integer.parseInt(txtMesAdq.getText()) > 0 && Integer.parseInt(txtMesAdq.getText()) < 13){
                    if(Integer.parseInt(txtAnioAdq.getText()) > 2010 && Integer.parseInt(txtAnioAdq.getText()) < 2100){
                        if(fechaMenorIgualHoy(txtDiaAdq.getText(),txtMesAdq.getText(),txtAnioAdq.getText())){
                            return true;
                        } else{
                            JOptionPane.showMessageDialog(null, "La fecha no puede superior a la actual");
                            return false;
                        }
                    } else return false;
                } else return false;
            } else return false;
        }catch(Exception e){
            return false;
        }
    }
    
    private boolean validarCampos(){
        if(txtMarca.getText().length() > 0){
            if(txtCodigo.getText().length() > 3 && txtCodigo.getText().length() < 9){
                if(validarFecha()){
                    return true;
                } else{
                    JOptionPane.showMessageDialog(null, "Error en la fecha ingresada");
                    return false;
                }
            } else{
                JOptionPane.showMessageDialog(null, "El codigo debe contener entre 4 y 8 caracteres");
                txtCodigo.requestFocus();
                return false;
            }
        } else{
            JOptionPane.showMessageDialog(null, "Ingrese la marca");
            txtMarca.requestFocus();
            return false;
        }
    }
    
    private void btnNewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewMouseClicked
        if(validarCampos()){
            try{
                EquipoAgricola nuevo_equipo = new EquipoAgricola();
                nuevo_equipo.setId_equipo(equipoSeleccionado.getId_equipo());
                nuevo_equipo.setId_estado(EquipmentController.obtenerIdEstadoPorNombre(cbxStates.getSelectedItem().toString()));
                nuevo_equipo.setId_tipo(EquipmentController.obtenerIdTipoPorNombre(cbxTypes.getSelectedItem().toString()));
                nuevo_equipo.setAdquisicion(txtAnioAdq.getText()+"-"+txtMesAdq.getText()+"-"+txtDiaAdq.getText());
                nuevo_equipo.setCodigo(txtCodigo.getText());
                nuevo_equipo.setMarca(txtMarca.getText());
                nuevo_equipo.setModelo(txtModelo.getText());
                nuevo_equipo.setDescripcion(txtDescripcion.getText());
                if(EquipmentController.actualizarEquipo(nuevo_equipo)){
                    EquipmentView form = new EquipmentView();
                    form.setVisible(true);
                    this.dispose();
                } else{
                    JOptionPane.showMessageDialog(null, "Error al actualizar el equipo");
                }
            } catch(Exception e){
                JOptionPane.showMessageDialog(null, "Error al actualizar el equipo. "+e.getMessage());
            }
        }
    }//GEN-LAST:event_btnNewMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateEquipmentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateEquipmentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateEquipmentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateEquipmentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateEquipmentView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBack1;
    private javax.swing.JLabel btnNew;
    private javax.swing.JComboBox<String> cbxStates;
    private javax.swing.JComboBox<String> cbxTypes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtAnioAdq;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtDiaAdq;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtMesAdq;
    private javax.swing.JTextField txtModelo;
    // End of variables declaration//GEN-END:variables
}
